site_name: Qiling Framework Documentation
site_description: Qiling Framework advanced binary analysis framework.
#site_favicon: 
site_url: https://qilingframework.readthedocs.org
repo_url: https://github.com/qilingframework/rtfd.git
theme: readthedocs
pages:
- 'index.md'
- 'getting_started.md'
- 'demo.md'
- 'debugger.md'
- 'register.md'
- 'memory.md'
